#ifndef LVND_COCOA_KEY_BINDINGS_H
#define LVND_COCOA_KEY_BINDINGS_H

#include "../input.h"

//Key bindings
#define LVND_TOTAL_NS_KEY_COUNT 127

typedef enum LvndNSKey {
    LVND_NS_KEY_A,
    LVND_NS_KEY_S,
    LVND_NS_KEY_D,
    LVND_NS_KEY_F,
    LVND_NS_KEY_H,
    LVND_NS_KEY_G,
    LVND_NS_KEY_Z,
    LVND_NS_KEY_X,
    LVND_NS_KEY_C,
    LVND_NS_KEY_V,
    LVND_NS_KEY_ISO_SECTION,
    LVND_NS_KEY_B,
    LVND_NS_KEY_Q,
    LVND_NS_KEY_W,
    LVND_NS_KEY_E,
    LVND_NS_KEY_R,
    LVND_NS_KEY_Y,
    LVND_NS_KEY_T,
    LVND_NS_KEY_D1,
    LVND_NS_KEY_D2,
    LVND_NS_KEY_D3,
    LVND_NS_KEY_D4,
    LVND_NS_KEY_D6,
    LVND_NS_KEY_D5,
    LVND_NS_KEY_EQUAL,
    LVND_NS_KEY_D9,
    LVND_NS_KEY_D7,
    LVND_NS_KEY_MINUS,
    LVND_NS_KEY_D8,
    LVND_NS_KEY_D0,
    LVND_NS_KEY_RIGHT_BRACKET,
    LVND_NS_KEY_O,
    LVND_NS_KEY_U,
    LVND_NS_KEY_LEFT_BRACKET,
    LVND_NS_KEY_I,
    LVND_NS_KEY_P,
    LVND_NS_KEY_RETURN,
    LVND_NS_KEY_L,
    LVND_NS_KEY_J,
    LVND_NS_KEY_QUOTE,
    LVND_NS_KEY_K,
    LVND_NS_KEY_SEMICOLON,
    LVND_NS_KEY_BACKSLASH,
    LVND_NS_KEY_COMMA,
    LVND_NS_KEY_SLASH,
    LVND_NS_KEY_N,
    LVND_NS_KEY_M,
    LVND_NS_KEY_PERIOD,
    LVND_NS_KEY_TAB,
    LVND_NS_KEY_SPACE,
    LVND_NS_KEY_GRAVE,
    LVND_NS_KEY_DELETE,

    LVND_NS_KEY_UNDEFINED0,

    LVND_NS_KEY_ESCAPE,

    LVND_NS_KEY_UNDEFINED1,

    LVND_NS_KEY_COMMAND,
    LVND_NS_KEY_SHIFT,
    LVND_NS_KEY_CAPS_LOCK,
    LVND_NS_KEY_OPTION,
    LVND_NS_KEY_CONTROL,
    LVND_NS_KEY_RIGHT_SHIFT,
    LVND_NS_KEY_RIGHT_OPTION,
    LVND_NS_KEY_RIGHT_CONTROL,
    LVND_NS_KEY_FUNCTION,

    LVND_NS_KEY_UNDEFINED2,

    LVND_NS_KEY_KEYPAD_DECIMAL,

    LVND_NS_KEY_UNDEFINED3,

    LVND_NS_KEY_KEYPAD_MULTIPLY,

    LVND_NS_KEY_UNDEFINED4,

    LVND_NS_KEY_KEYPAD_PLUS,

    LVND_NS_KEY_UNDEFINED5,

    LVND_NS_KEY_KEYPAD_CLEAR,
    LVND_NS_KEY_VOLUME_UP,
    LVND_NS_KEY_VOLUME_DOWN,
    LVND_NS_KEY_MUTE,
    LVND_NS_KEY_KEYPAD_DIVIDE,
    LVND_NS_KEY_KEYPAD_ENTER,

    LVND_NS_KEY_UNDEFINED6,

    LVND_NS_KEY_KEYPAD_MINUS,
    LVND_NS_KEY_F18,
    LVND_NS_KEY_F19,
    LVND_NS_KEY_KEYPAD_EQUALS,
    LVND_NS_KEY_KEYPAD0,
    LVND_NS_KEY_KEYPAD1,
    LVND_NS_KEY_KEYPAD2,
    LVND_NS_KEY_KEYPAD3,
    LVND_NS_KEY_KEYPAD4,
    LVND_NS_KEY_KEYPAD5,
    LVND_NS_KEY_KEYPAD6,
    LVND_NS_KEY_KEYPAD7,
    LVND_NS_KEY_F20,
    LVND_NS_KEY_KEYPAD8,
    LVND_NS_KEY_KEYPAD9,
    LVND_NS_KEY_JIS_YEN,
    LVND_NS_KEY_JIS_UNDERSCORE,
    LVND_NS_KEY_JIS_KEYPAD_COMMA,
    LVND_NS_KEY_F5,
    LVND_NS_KEY_F6,
    LVND_NS_KEY_F7,
    LVND_NS_KEY_F3,
    LVND_NS_KEY_F8,
    LVND_NS_KEY_F9,
    LVND_NS_KEY_JIS_EISU,
    LVND_NS_KEY_F11,
    LVND_NS_KEY_JIS_KANA,
    LVND_NS_KEY_F13,
    LVND_NS_KEY_F16,
    LVND_NS_KEY_F14,

    LVND_NS_KEY_UNDEFINED7,

    LVND_NS_KEY_F10,

    LVND_NS_KEY_UNDEFINED8,

    LVND_NS_KEY_F12,

    LVND_NS_KEY_UNDEFINED9,

    LVND_NS_KEY_F15,
    LVND_NS_KEY_HELP,
    LVND_NS_KEY_HOME,
    LVND_NS_KEY_PAGE_UP,
    LVND_NS_KEY_FORWARD_DELETE,
    LVND_NS_KEY_F4,
    LVND_NS_KEY_END,
    LVND_NS_KEY_F2,
    LVND_NS_KEY_PAGE_DOWN,
    LVND_NS_KEY_F1,
    LVND_NS_KEY_LEFT_ARROW,
    LVND_NS_KEY_RIGHT_ARROW,
    LVND_NS_KEY_DOWN_ARROW,
    LVND_NS_KEY_UP_ARROW
} LvndNSKey;

LvndKey KeyNSToLvndBindings[LVND_TOTAL_NS_KEY_COUNT] = {
    LVND_KEY_A,
    LVND_KEY_S,
    LVND_KEY_D,
    LVND_KEY_F,
    LVND_KEY_H,
    LVND_KEY_G,
    LVND_KEY_Z,
    LVND_KEY_X,
    LVND_KEY_C,
    LVND_KEY_V,

    LVND_KEY_UNDEFINED,

    LVND_KEY_B,
    LVND_KEY_Q,
    LVND_KEY_W,
    LVND_KEY_E,
    LVND_KEY_R,
    LVND_KEY_Y,
    LVND_KEY_T,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_EQUAL,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_MINUS,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_RIGHT_BRACKET,
    LVND_KEY_O,
    LVND_KEY_U,
    LVND_KEY_LEFT_BRACKET,
    LVND_KEY_I,
    LVND_KEY_P,
    LVND_KEY_ENTER,
    LVND_KEY_L,
    LVND_KEY_J,

    LVND_KEY_UNDEFINED,

    LVND_KEY_K,
    LVND_KEY_SEMICOLON,
    LVND_KEY_BACKSLASH,
    LVND_KEY_COMMA,
    LVND_KEY_SLASH,
    LVND_KEY_N,
    LVND_KEY_M,
    LVND_KEY_PERIOD,
    LVND_KEY_TAB,
    LVND_KEY_SPACE,
    LVND_KEY_GRAVE_ACCENT,
    LVND_KEY_DELETE,

    LVND_KEY_UNDEFINED,

    LVND_KEY_ESCAPE,

    LVND_KEY_UNDEFINED,

    LVND_KEY_LEFT_SUPER,
    LVND_KEY_LEFT_SHIFT,
    LVND_KEY_CAPS_LOCK,
    LVND_KEY_LEFT_ALT,
    LVND_KEY_LEFT_CONTROL,
    LVND_KEY_RIGHT_SHIFT,
    LVND_KEY_RIGHT_ALT,
    LVND_KEY_RIGHT_CONTROL,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_KP_DECIMAL,

    LVND_KEY_UNDEFINED,

    LVND_KEY_KP_MULTIPLY,

    LVND_KEY_UNDEFINED,

    LVND_KEY_KP_ADD,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_KP_DIVIDE,
    LVND_KEY_KP_ENTER,

    LVND_KEY_UNDEFINED,

    LVND_KEY_KP_SUBTRACT,
    LVND_KEY_F18,
    LVND_KEY_F19,
    LVND_KEY_KP_EQUAL,
    LVND_KEY_KP_0,
    LVND_KEY_KP_1,
    LVND_KEY_KP_2,
    LVND_KEY_KP_3,
    LVND_KEY_KP_4,
    LVND_KEY_KP_5,
    LVND_KEY_KP_6,
    LVND_KEY_KP_7,
    LVND_KEY_F20,
    LVND_KEY_KP_8,
    LVND_KEY_KP_9,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_UNDEFINED,

    LVND_KEY_F5,
    LVND_KEY_F6,
    LVND_KEY_F7,
    LVND_KEY_F3,
    LVND_KEY_F8,
    LVND_KEY_F9,

    LVND_KEY_UNDEFINED,

    LVND_KEY_F11,

    LVND_KEY_UNDEFINED,

    LVND_KEY_F13,
    LVND_KEY_F16,
    LVND_KEY_F14,

    LVND_KEY_UNDEFINED,

    LVND_KEY_F10,

    LVND_KEY_UNDEFINED,

    LVND_KEY_F12,

    LVND_KEY_UNDEFINED,

    LVND_KEY_F15,

    LVND_KEY_UNDEFINED,

    LVND_KEY_HOME,
    LVND_KEY_PAGE_UP,

    LVND_KEY_UNDEFINED,

    LVND_KEY_F4,
    LVND_KEY_END,
    LVND_KEY_F2,
    LVND_KEY_PAGE_DOWN,
    LVND_KEY_F1,
    LVND_KEY_LEFT,
    LVND_KEY_RIGHT,
    LVND_KEY_DOWN,
    LVND_KEY_UP
};

#endif
