#ifndef LVND_WINDOW_PARAMS_H
#define LVND_WINDOW_PARAMS_H

#define LVND_TOTAL_WINDOW_PARAM_COUNT 2

typedef enum LvndWindowParam {
    LVND_WINDOW_PARAM_OPENGL_VERSION_MAJOR,
    LVND_WINDOW_PARAM_OPENGL_VERSION_MINOR
} LvndWindowParam;

#endif
